baseURL = 'https://www.ajgreengrove.com/'
languageCode = 'en-us'
title = "A J Greengrove's Site"

summaryLength = 1

theme = 'ananke'

[taxonomies]
category = 'categories'
tag = 'tags'

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "Home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 2
[[menu.main]]
identifier = "works"
name = "Works"
url = "/categories/works"
weight = 3
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 4
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 5
