baseURL = 'https://www.ajgreengrove.com/'
languageCode = 'en-us'
summaryLength = 1
title = "A J Greengrove's Site"
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

