baseURL = 'https://www.ajgreengrove.com/'
locale = 'en-us'
title = "A J Greengrove"
theme = 'hugo-bearblog'
summaryLength = 1

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = "ajgreengrove"
    name = "A J Greengrove"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

[params]
  description = "A J Greengrove - Environment Forensics & Build Architecture"
  # favicon = "/favicon.ico" # not for consultancy
  # Set this if you want the "next post" navigator at the bottom of pages
  enablePostNavigator = true
  hideMadeWithLine = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true # Required if ox-hugo exports include raw HTML blocks
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
  [markup.highlight]
    noClasses = false
    lineNos = false
    lineNumbersInTable = false
    codeFences = true
    guessSyntax = true
