baseURL = 'https://www.ajgreengrove.com/'
languageCode = 'en-us'
title = "A. J. Greengrove's Site"
theme = 'ananke'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup.goldmark.renderer]
  unsafe = true
